= Boot-Demo

Simple project for:

- a simple Python web app
- packing it in separate containers for amd64 and arm64 platforms
- pushing these two images to an ECR repo
- creating a multi-platform manifest for them
- creating an oci multi-platform image
- pushing it to an ECR Repo
- pulling it back to test it
- deploying this app on Kubernetes using helm

NOTE: I named it boot-demo, because hopefully it bootstraps my knowledge of all these things. :D

== Build the Docker image

In this directory run:

[source, shell]
----
docker build -t boot-demo:1.0 .
----

To deploy the image and test it:

[source, shell]
----
docker run -d -p 8080:8080 boot-demo:1.0
----

== Set up the Environment

You will need all these env variables in your terminal,  so you can just copy-paste the commands in the docs.

[source,shell]
----
# set up environment
export AWS_ACCESS_KEY_ID=".."
export AWS_SECRET_ACCESS_KEY=".."
export AWS_SESSION_TOKEN=".."
export REGION=eu-west-1
export AWS_ACCOUNT=..
export IMAGE_NAME=boot-demo

# set up the AWS bits
echo "... login into ECR ..."
aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com

echo "... create ECR repository ..."
aws ecr create-repository --repository-name ${IMAGE_NAME} --image-scanning-configuration scanOnPush=true --region ${REGION}
----

From here on follow whichever you are interested in:

* link:docs/docker-multi-platform.adoc[Building the Multi-Platform Docker Image]
* link:docs/docker-multi-platform.adoc[Building the Multi-Platform OCI Image using Docker Buildx]
* link:docs/podman-multi-platform.adoc[Building the Multi-Platform OCI Image using Podman]

But eventually you will end here: link:docs/copy-image-between-repositories.adoc[copying your multi-platform image between repositories].

Just in case you want to, once you have the image you can also pack it as a Helm chart and deploy it on Kubernetes or use it in a helm chart.

== Pack the Chart & Deploy on kubernetes

IMPOTANT: Before packing the chart, edit the link:helm-demo/values.yaml[values.yaml] and replace `${AWS_ACCOUNT}` and `{REGION}` with the concrete values.

[source, shell]
----
kubectl create namespace helm-demo
kubectl create secret docker-registry ecrcred \
    --docker-server=${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
    --docker-username=AWS \
    --docker-password=$(aws ecr get-login-password) \
    --namespace=helm-demo
kubectl config set-context --current --namespace=helm-demo

# package the chart
helm package helm-demo -u
# do a mock install
helm install helm-demo helm-demo-0.0.1.tgz --dry-run
# do the actuall install
helm install helm-demo helm-demo-0.0.1.tgz --namespace=helm-demo

kubectl get all,cm,secret,ing,pv,pvc

# at the end - nuke everything
helm uninstall helm-demo
kubectl delete namespace helm-demo
----

== Push the Helm Chart to ECR

[source, shell]
----
# helm login
 aws ecr get-login-password --region $REGION |  helm registry login --username AWS --password-stdin "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com"
CHART_NAME=helm-demo
CHART_VERSION="0.0.1"
# create the repo
aws ecr create-repository --repository-name ${CHART_NAME} --region ${REGION}

TARGET_HELM_REPO="${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${CHART_NAME}"
helm push "${CHART_NAME}-${CHART_VERSION}.tgz" oci://${TARGET_HELM_REPO%/*}

# test
helm pull oci://$TARGET_HELM_REPO --version $CHART_VERSION

# create namespace, set default context, etc. works on nay kubernetes cluster
helm install helm-demo helm-demo --namespace=helm-demo
----