= Boot-Demo

Simple project for:

- a simple Python web app
- packing it in separate containers for amd64 and arm64 platforms
- pushing these two images to an ECR repo
- creating a multi-platform manifest for them
- creating an oci multi-platform image
- pushing it to an ECR Repo
- pulling it back to test it
- deploying this app on Kubernetes using helm

TIP: I named it boot-demo, because hopefully it bootstraps my knowledge of all these things. :D

== Build the Docker image

In this directory run:

[source, shell]
----
docker build -t boot-demo:1.0 .
----

To deploy the image and test it:

[source, shell]
----
docker run -d -p 8080:8080 boot-demo:1.0
----

== Set up the Environment

You will need all these env variables in your terminal,  so you can just copy-paste the commands in the docs.

[source,shell]
----
# set up environment
export AWS_ACCESS_KEY_ID=".."
export AWS_SECRET_ACCESS_KEY=".."
export AWS_SESSION_TOKEN=".."
export REGION=eu-west-1
export AWS_ACCOUNT=..
export IMAGE_NAME=boot-demo

# set up the AWS bits
echo "... login into ECR ..."
aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com

echo "... create ECR repository ..."
aws ecr create-repository --repository-name ${IMAGE_NAME} --image-scanning-configuration scanOnPush=true --region ${REGION}
----

From here on follow whichever you are interested in:

* link:docs/docker-multi-platform.adoc[Building the Multi-Platform Docker Image]
* link:docs/docker-multi-platform.adoc[Building the Multi-Platform Docker Image]

IMPORTANT: link:docs/the-problem.adoc[The problem] lists the three attempts of solving the issue of re-locating a multi-platform image while keeping it an OCI image, so an ECR registry accepts a push.

== Deploy on kubernetes

[source, shell]
----
kubectl create namespace helm-demo
kubectl create secret docker-registry ecrcred \
    --docker-server=${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
    --docker-username=AWS \
    --docker-password=$(aws ecr get-login-password) \
    --namespace=helm-demo
kubectl config set-context --current --namespace=helm-demo

# package the chart
helm package helm-demo -u
# do a mock install
helm install helm-demo helm-demo-0.0.1.tgz --dry-run
# do the actuall install
helm install helm-demo helm-demo-0.0.1.tgz --namespace=helm-demo

kubectl get all,cm,secret,ing,pv,pvc

# at the end - nuke everything
helm uninstall helm-demo
kubectl delete namespace helm-demo
----

== Push the Helm Chart to ECR

TODO