= The Problem

For creating an addon we assume the customer provides us with a multi-platform OCI image URL like `"${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1"`

For creating an add-on we need to pull this image, re-tag it and push it to the Marketplace Repo. This is a bit tricky to do with multi-platform images. Below there are a few sections for every what that did not work.

== Re-tagging and Pushing Without Pulling the Image

link:https://stackoverflow.com/questions/74066597/how-to-tag-multi-architecture-docker-image-and-push-the-newly-tagged-image[Source of inspiration]

[source, shell]
----
AWS_ACCOUNT_OTHER=304295633295 # different than AWS_ACCOUNT
REGION_OTHER=eu-west-1 # different than REGION
# set up the AWS bits
echo "... login into ECR ..."
aws ecr get-login-password --region ${REGION_OTHER} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_OTHER}.dkr.ecr.${REGION_OTHER}.amazonaws.com

echo "... create ECR repository ..."
aws ecr create-repository --repository-name oci-boot --image-scanning-configuration scanOnPush=true --region ${REGION_OTHER}

OLD_TAG="${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1"
NEW_TAG="${AWS_ACCOUNT_OTHER}.dkr.ecr.${REGION_OTHER}.amazonaws.com/${IMAGE_NAME}:1.1-1708080898"

docker buildx imagetools create --tag "$NEW_TAG" "$OLD_TAG" # !!!

# inspect the manifest
docker manifest inspect "${AWS_ACCOUNT_OTHER}.dkr.ecr.${REGION_OTHER}.amazonaws.com/${IMAGE_NAME}:1.1-1708080898"
----

IMPORTANT: If `AWS_ACCOUNT_OTHER == AWS_ACCOUNT && REGION_OTHER == REGION`, which means the images are pushed to the same ECR, the manifest is created correctly, and it contains `"mediaType": "application/vnd.oci.image.manifest.v1+json"` so, mucho bueno!!!

CAUTION: If `AWS_ACCOUNT_OTHER != AWS_ACCOUNT || REGION_OTHER != REGION`, calling `aws ecr get-login-password... | docker login...` logs out from the repo where the image is hosted and all goes wrong. No manifest is created.

== Pulling the Image, Expanding it and Re-creating it

[source, shell]
----
# ARM64
TAG_ONE=$(docker buildx imagetools inspect --raw "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" | jq '.manifests[0].platform.architecture' | sed 's/\"//g')
PLATFORM_ONE=$(docker buildx imagetools inspect --raw "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" | jq '.manifests[0].platform.os' | sed 's/\"//g')/${TAG_ONE}
docker pull --platform $PLATFORM_ONE "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1"
docker tag "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2-${TAG_ONE}"
docker push "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2-${TAG_ONE}"

# AMD64
TAG_TWO=$(docker buildx imagetools inspect --raw "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" | jq '.manifests[1].platform.architecture' | sed 's/\"//g')
PLATFORM_TWO=$(docker buildx imagetools inspect --raw "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" | jq '.manifests[1].platform.os' | sed 's/\"//g')/${TAG_TWO}
docker pull --platform $PLATFORM_TWO "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1"
docker tag "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2-${TAG_TWO}"
docker push "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2-${TAG_TWO}"

export DOCKER_CLI_EXPERIMENTAL=enabled
docker manifest create \
    "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2" \
    --amend "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2-${TAG_ONE}" \
    --amend "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2-${TAG_TWO}"

docker manifest inspect "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2"
docker manifest push "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.2" # !!!
----

CAUTION: You can create the manifest, but you can't push it to ECR, because `"application/vnd.docker.distribution.manifest.v2+json"`.

== Push It to a New ECR Repo using manifest files

[source, shell]
----
echo "... login into source ECR ..."
aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com

# generate the manifest files for each platform
docker buildx imagetools inspect --raw "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" | jq '.manifests[] |select(.platform.architecture |contains("arm"))' > descriptor_arm.json
docker buildx imagetools inspect --raw "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.1" | jq '.manifests[] |select(.platform.architecture |contains("amd"))' > descriptor_amd.json
----

Push it to the same ECR registry:

[source, shell]
----
docker buildx imagetools create -t "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.3" -f descriptor_amd.json -f descriptor_arm.json
docker manifest inspect "${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:1.3"
----

This approach works within the same ECR repository.

IMPORTANT: The manifest contains `"mediaType": "application/vnd.oci.image.manifest.v1+json"` so, mucho bueno!!!

Push it to another ECR registry:

[source, shell]
----

REGION_OTHER=us-east-1 # just change the region
echo "... login into destination ECR - in this case we just use a different region..."
aws ecr get-login-password --region ${REGION_OTHER} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_OTHER}.dkr.ecr.${REGION_OTHER}.amazonaws.com

echo "... create ECR repository ..."
aws ecr create-repository --repository-name boot-demo --image-scanning-configuration scanOnPush=true --region ${REGION_OTHER}

# push the multi-platform image
docker buildx imagetools create -t "${AWS_ACCOUNT}.dkr.ecr.${REGION_OTHER}.amazonaws.com/${IMAGE_NAME}:1.3" -f descriptor_amd.json -f descriptor_arm.json
----

IMPORTANT: This approach does not work when source and destination registries are different. Docker login cannot hold two sessions at once. !!!

CAUTION: This is the result we get:  `ERROR: httpReadSeeker: failed open: content at https://304295633295.dkr.ecr.us-east-1.amazonaws.com/v2/boot-demo/manifests/sha256:ab8582a9cf7f6546a390b55fef29eba60db98d01504aca929d0c18a17d938ef4 not found: not found`
`

